### ISSUE TITLE
Don't require GLIBCXX_3.4.26

### ISSUE THREAD

**Issue by ezyang** [ptillet/triton-llvm-releases#6]
It would be super handy if these releases were built against an older version of glibcxx (for my particular env, 3.4.25 or earlier would work), so that these LLVM binaries can work with OSes whose glibcxx is not bleeding edge. I could submit a PR if people agree this is OK to do.

**Comment by ezyang** [comment]
Actually, by code reading, you do have centos builds. I'll figure out why setup.py is not taking them.

**Comment by anisse** [comment]
@ezyang  Did you manage to build a centos 8 release for the toolchain ?

**Comment by ezyang** [comment]
I ended up using PyTorch's triton binaries at https://download.pytorch.org/whl/nightly/ , which works on my system.
